Implemented SuggestionsManager, ButtonStep, and StepManager in compliance with our CRC cards design
edwardhuahan/tli-speakfluid pull request #55
Opened 2022-11-13 21:21 UTC by auroraborie

created the SuggestionsManager, ButtonStep, and StepManager classes in compliance with the entities layer of our clean architecture design. This allows functionality of our program to analyze the transcript and be able to find an optimal talk step when called by the use case interactor. It is significant in that we are following the Single Responsibility Principal for each class and having our implementations in the higher level entities of SuggestionManager and StepManager depend on abstractions of TalkStep and Scorable rather than concrete implementations.

2022-11-14 22:11 UTC, nm-le commented
Looks good to me! Will the keywords be case sensitive?

2022-11-14 22:13 UTC, nm-le approved these changes

2022-11-16 22:08 UTC, Lemiex requested changes
minor change but for ButtonStep, i think i would be a good idea to put stepName assignment outside, since it never changes anyway. 
private final String stepName = "Button";

2022-11-17 00:42 UTC, edwardhuahan commented
See https://github.com/edwardhuahan/tli-speakfluid/pull/69

2022-11-17 00:42 UTC, closed without merging