Implemented Capture and Choice Step entities
edwardhuahan/tli-speakfluid pull request #64
Opened 2022-11-15 23:04 UTC by Lemiex

**CaptureStep** Notes and Discussion Points:
Notes:
1. Chatbot keywords contain themes: email, order number, time/date, address, name, asking for information (e.g. "please provide")
2. User keywords contain themes: email (@ .com), times/date (PM, AM, Monday), Address
3. hasNumbers(), isZipCode(), isEmail() use regular expressions for checking numbers (e.g. phone, order number, insturction), zip codes, and emails 
Points for discussion:
1. In runAnalysis(), I included both the search for keywords (@ .com email) AND isEmail(). That means, if a user did enter an email, the score for using an email would be counted twice. I kept it this way for now because I thought the keyword each was much weaker than the RegEx isEmail() search, so it acts as a double security. And what can go wrong if the score is high? We know it's an email and thus we recommend a capture step for sure. This applies for email, number, and zipcode.
Let me know your thoughts:

**ChoiceStep** notes:
1. ChoiceStep just uses the predefined common analysis methods from TalkStep, and runs them in runAnalysis() 
2. The keywords are ranked from high -> low in weighting, highest 5, lowest 1. This way then the for loop breaks because a keyword matched, the highest score is added to scoreAccumulator. 
3. ChoiceStep is mainly for identifying when users answer "Yes" or "No", since according to voiceflow's blog, is it's usage.

2022-11-16 03:03 UTC, auroraborie approved these changes
Hey Sarah,

I reviewed your PR just now and think this adheres to all of our design decisions which is great. I think implementing the hasNumbers(), isZipCode(), isEmail() as well as having great targeted keyword mapping clusters for both the user and chatbot are really good metrics for the capture step. 

Also, I really noticed how thorough your documentation with the java docs are! Great job.

I think the logic is sound but just one small note: we may need to discuss a little more about the final weightings of the confidence score calculation and what the max score for each TalkStep child class should be but otherwise I approve with a happy face :)

2022-11-16 03:48 UTC, auroraborie requested changes
Hi Sarah,

I actually did have one more note, and I mentioned this with Zoey as well. For the chatbot and user keyword mappings, I originally thought each mapping would share the same score since they contain variations of the same intent. 

I noticed in your CaptureStep for example that in the same Map, "please provide" had a score of 5.0 and "provide your" had a score of 4.0. However, they share the same meaning so I think it makes sense to weigh them the same. This way as well, when we break out of the inner for loop then this does not affect the score accumulator since all of the rest of the phrases will have the same score and we know our score is more accurate since we wouldn't miss any higher or lower values. 

So I suggest your change the mappings to have uniform scoring within each Map. Please give me your thoughts :)

2022-11-16 07:01 UTC, ZZBP requested changes
Hi Sarah! Amazing work implementing the two talk steps! 
For CaptureStep, I think it is very thoughtful to apply regx to help determine if the dialogue hits the features of a capture step more precisely. As mentioned by Rory, the documentation is very throughout and easy to follow. 

One thing I hope you could help me clarify is about the method isZipCode(). Line 92 you added a break and could you elaborate a bit on why the other methods that share a similar structure do not include a break?

Two tiny details for the attributes: 
1. Could you add an instance variable `private String stepName` to both classes for the purpose of in higher level class StepManager we will have the option to access the name of the step? 
2. This does not require change, but for scoreAccumulator, why is it static?

2022-11-16 22:13 UTC, Lemiex commented
Zoey, thanks for your pointers
For thanks for pointing of the inconsistency in 'break'. I actually meant to include a break for all two is___ methods! This is because if we know there is an email/zipcode in the message, its an extremely good indicator to use CaptureStep already. No need to keep adding 10 to the scoreAccumulator -- it might make the score to large, AND there would be no way to set a maxScore. 
1. Done!
2. i reailsed this was a mistake and took 'static' off.
3. Discussed in discord!

2022-11-16 22:14 UTC, Lemiex commented
Rory, we certainly need to discuss the weightings and maxScore! I will push what i have so far and we can decide and come back and make changes since it wouldn't be a huge fix

2022-11-16 22:57 UTC, ZZBP approved these changes
Amazing work! Love that you made sure every time we pull, java will be the source root!!! The confidenceScore in your step entities will not be used but it will just be a quick fix for later!

2022-11-17 00:00 UTC, auroraborie approved these changes

2022-11-17 00:01 UTC, merged