Implemented StepSuggestionInteractor
edwardhuahan/tli-speakfluid pull request #71
Opened 2022-11-17 01:06 UTC by ZZBP

Updated the return type of confidenceScore in Dialogue;

Implemented StepSuggestionInteractor for our second use case partially. Still need to implement the part for accessing parsed transcript and outputing the suggestions.

2022-11-17 18:28 UTC, Lemiex approved these changes
Couldn't find a thing to fix. Great job Zoey!

2022-11-17 21:54 UTC, auroraborie requested changes
Hey Zoey, 

Good work! I did notice that in accordance with a clean architecture design, the use case interactor should implement an input boundary interface, and accept the input data as a parameter. So before we merge this, could you first have UsecaseInteractor implement a Input Boundary interface? This is just so we do not depend on concretions but abstractions. 

Thanks for the PR!

2022-11-18 03:22 UTC, ZZBP commented
Hi Aurora! Amazing point! It is definitely essential for us to have the input boundary interface which the use case interaction will implement! Thank you so much for the insight! I have added the input boundary and updated the use case interactor!

2022-11-20 03:52 UTC, auroraborie approved these changes
Hey Zoey this addresses the new features we talked about, of returning the top three choices if none of the talksteps have a confidence score above 70% so good work! I have a PR that will change the name of StepManager and SuggestionManager to a ConfidenceScoreCalculator and ConfidenceScoreOptimizer so you will have to update that after. But I will approve this now.

2022-11-20 22:40 UTC, nm-le requested changes
Great job on adhering to the SOLID principles and clean architecture :) I have some questions and suggestions to change:

1. Do we store confidenceScore in the analyzed transcript and display that to users? Right now I can see that we are only storing the suggested talk step in transcript, but not its corresponding confidenceScore. If we do want to store the score then it should be normalized. Also are we suggesting multiple talk steps (ranked) or just one?

2. In light of the upcoming changes to abstractify Dialogue, we should consider changing methods' names, one of which is analyzeTranscript. But let's merge this branch first.

3. In Dialogue.java: stepSuggestion and confidenceScore are now arraylists and thus should be named accordingly to avoid confusion. For example stepSuggestionList. Line 41 is an example of such confusion (this.confidenceScore.add(confidenceScore);)

4. In TranscriptAnalysisInteractor.java: I want to suggest some changes to the docstring (line 43-54) of analyzeTranscript:
Line 50: Dialogue is a back-and-forth interaction, not conversation. Conversation is defined as one session (or a list of Dialogue objects) corresponding to a conversation id.
Line 51: Speech should be changed to Message

I really like how your code is well-documented. Let's merge soon so we can get on to make the changes in Dialogue.

2022-11-21 23:05 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/usecases/TranscriptAnalysisInputBoundary.java
> +public interface TranscriptAnalysisInputBoundary {
I like the naming and following conventions great work

2022-11-21 23:06 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/usecases/TranscriptAnalysisInteractor.java
> +package com.speakfluid.backend.usecases;
Good idea, I was not a fan of naming a class UsecaseInteractor since it didn't make much sense to me

2022-11-21 23:07 UTC, edwardhuahan approved these changes
I'm glad someone finally got rid of UsecaseInteractor.java

2022-11-23 21:22 UTC, nm-le approved these changes

2022-11-23 21:23 UTC, merged