Changed LoadTranscript to be TranscriptLoader and added documentation.
edwardhuahan/tli-speakfluid pull request #72
Opened 2022-11-17 04:14 UTC by zhg-kj

I corrected the naming convention problem of LoadTranscript by renaming it as the noun TranscriptLoader. 

I also added documentation for the files:
- TranscriptLoader.java
- TranscriptController.java
- TranscriptService.java

2022-11-17 04:50 UTC, Lemiex approved these changes
Documentation was helpful! I still think “Transcript” makes the most sense as a name as opposed to TranscriptLoader, but not a big deal so i approved if you want to stick with your naming

2022-11-17 05:02 UTC, zhg-kj commented
> 

The issue with simply Transcript is that I think that implies that it is an entity but it really isn’t an entity. It is basically just a model with functions that are used directly on files in the DB

2022-11-17 05:03 UTC, zhg-kj commented
> The issue with simply Transcript is that I think that implies that it is an entity but it really isn’t an entity. It is basically just a model with functions that are used directly on files in the DB



> Documentation was helpful! I still think “Transcript” makes the most sense as a name as opposed to TranscriptLoader, but not a big deal so i approved if you want to stick with your naming

The issue with simply Transcript is that I think that implies that it is an entity but it really isn’t an entity. It is basically just a model with functions that are used directly on files in the DB.

2022-11-21 23:08 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/model/TranscriptLoader.java
> +    private String transcriptName;
I'm a fan of this naming convention nice

2022-11-21 23:09 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/service/TranscriptService.java
>  public class TranscriptService {
Is there a better name for this? I can't rmr if they call this type of class a Gateway or something

2022-11-21 23:10 UTC, edwardhuahan requested changes
Need to fix the merge conflict with Suggestion.java

2022-11-23 21:20 UTC, edwardhuahan approved these changes

2022-11-23 21:34 UTC, merged