Added JUnit dependencies, created SpeechTests and DialogueTests.
edwardhuahan/tli-speakfluid pull request #77
Opened 2022-11-19 21:14 UTC by zhg-kj

In this PR I installed the JUnit dependencies required for testing and created tests for the Speech and Dialogue classes.

That said, testing is all CONFIGURED. If you want to write tests please follow the instructions below.

> When you create tests, make sure that your file paths MIRROR the file paths of the file that you are testing.
> 
>![image](https://user-images.githubusercontent.com/67027837/202871819-c5340f6b-4c64-41b6-aa50-317d2fe0d750.png)
>
> You will notice that under backend there are two main directories: main and test. If, for example, you want to create a test for the class Speech, you need to mirror the file path of Speech.java from the main directory for your testing file SpeechTests.java in the test directory.
> 
> To set up, use the SpeechTests.java file as a template. If there are specific tests you want to create refer to https://www.baeldung.com/junit-5 for support.
> 
> You DO NOT need to import the original file. Notice that SpeechTests does not import Speech. The compiler is smart enough to understand what you mean IF you organize the file path correctly.
> 
> To run your tests cd into backend and run mvn test -Dtest=NameOfTestFile (no need for .java)

I have requested everyone as a reviewer so we are all on the same page for writing tests.

2022-11-20 19:55 UTC, Lemiex requested changes
Thanks for setting us up for testing Kai! The instructions were detailed too. Mirroring file paths makes sense as well.

Could you change SpeechTests to WozMessageTests? Since I believe we changes "Speech" to "WozMessage".

2022-11-21 23:16 UTC, edwardhuahan commented
> Thanks for setting us up for testing Kai! The instructions were detailed too. Mirroring file paths makes sense as well.
> 
> Could you change SpeechTests to WozMessageTests? Since I believe we changes "Speech" to "WozMessage".

I agree with this

2022-11-23 21:21 UTC, Lemiex approved these changes

2022-11-23 21:27 UTC, nm-le approved these changes

2022-11-24 00:01 UTC, auroraborie approved these changes
Hey Kai,
I think your PR is very helpful for helping us structure our own JUnit tests. Good work!

2022-11-24 02:39 UTC, merged