Amended ConfidenceScoreOptimizer and WozWozTranscriptAnalysisInteractor
edwardhuahan/tli-speakfluid pull request #97
Opened 2022-11-27 01:41 UTC by auroraborie

amended ConfidenceScoreOptimizer to return the ranked talksteps by their confidence score in decreasing order as an ArrayList of Maps. Made the corresponding changes to WozWozTranscriptAnalysisInteractor to be compatible with these changes so that the same functionality remains.

2022-11-27 02:24 UTC, Lemiex requested changes
Thanks for being so speedy on changing the Optimizer!!
1. you mightve accidentally changed TalkStep, but don't alter it! The correct version is already merged with main, see if you can restore the 'break' that you deleted and push again. If that makes the TalkStep change go away in this PR, great, if not, go to the TalkStep currently on our github and just copy paste the whole file and push it again so it's the right version
2. Update the documentation in the Interactor line 77, since we're returning all the talksteps now
3. Super minimal and up to you but i thought for Optimzier, rankSuggestions() might be a better method name than findSuggestedTalkSteps(), since we aren't rly "finding" them
4. I like your BeforeEach init(). method, it's concise. i was trying to write somthing similar and it was like so long TAT
5. ButtonSteptests - i appreicate your work for testUserMsgLength() on line 94 but it's not a responsibility for ButtonStep. for clarity of class responsibility, gotta leave all those tests to TalkStep
6. ButtonSteptests - what is line 34-46 the keyword lists for? you don't use them in the tests
7. ButtonStepTests - you might be missing tests for getMaxScore, getScoreAccumulator, and runAnalysis()
8. For methods like runAnalysis(), getScoreAccumulator(), setZeroAccumulator(), you might wanna play with some combination since they depend on runAnalysis() already happening
9. When you test runAnalysis(), use mock functions for countMatchKeywords() and calculateMsgLength(). Specific implementation: ` TalkStep talkStep = mock(TalkStep.class);
        when(talkStep.calculateMsgLength(user1)).thenReturn(10);` and write a similar one for countMatchKeywords()
The purpose of this is to test ButtonStep independently of TalkStep -- even if TalkStep's method fails, it won't be "blamed" on ButtonStep. Hope that makes sense! Ekagra went over it during our call today,  you can visit[ this link](https://semaphoreci.com/community/tutorials/stubbing-and-mocking-with-mockito-2-and-junit) he shared if u want

2022-11-27 02:48 UTC, Lemiex requested changes
Sorry I realised there were a few things I forgot to cover, these all address ButtonStepTests:
1. the trace_type should be either "request" - user, "response" - chat
2. in init(), I think you got the userMsg and chatbotMsg for dialogue object mistaken: from the 3 user and 3 chtatbot messages, you should be able to make 3 dialogues:
dialogue1 has chat1 as chatbotMsg, user2 as userMsg
dialogue2 has chat 2 as chatbotMsg, user3 for userMsg
dialogue3 has chat3 as chatbotMsg, and empoty userMsg
Recall that one dialogue is ONE back and forth, that starts when a chatbot speaks, and ends before the next chatbot message 
Also recall that we ignore the first user message in a conversation since there is no chatbot output to recommend. This is also documented in the parser

2022-11-27 17:01 UTC, auroraborie commented
Hey Sarah 
thank you for all the feedback. I incorporated the changes. I also incorporated the 'max cap' feature we discussed in ConfidenceScoreOptimizer to address situations where the scoreAccumulator exceed the maxscore. You should find no further issue here.

2022-11-27 17:30 UTC, Lemiex approved these changes
Beautiful, just one last change to implement I commented in the code :

2022-11-27 17:30 UTC, Lemiex commented on backend/src/test/java/com/speakfluid/backend/entities/CardStepTests.java
> +                "can you tell me some suggestions?");
change trace_type

2022-11-28 03:05 UTC, auroraborie commented on backend/src/test/java/com/speakfluid/backend/entities/CardStepTests.java
> +                "can you tell me some suggestions?");
oh good catch!

2022-11-30 03:37 UTC, edwardhuahan commented
Hey Aurora are you able to merge this branch with the main branch? I'm not sure why the Github Actions stopped working for this branch

2022-11-30 03:38 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/entities/ButtonStep.java
>      private final List<Map<String, Double>> chatbotKeywordsScoreMap = Arrays.asList(
Is there a better way of accomplishing this rather than having all of these similar lines of code? It's not as easy to read the code

2022-11-30 03:38 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/entities/ButtonStep.java
>      private final List<Map<String, Double>> chatbotKeywordsScoreMap = Arrays.asList(
Is there a better way of accomplishing this rather than having all of these similar lines of code? It's not as easy to read the code

2022-11-30 03:39 UTC, edwardhuahan commented on backend/src/test/java/com/speakfluid/backend/entities/ButtonStepTests.java
> +    ArrayList<WozMessage> userMsgs1 = new ArrayList<>();
Is there a reason that these have to remain separated? I think this could be better accomplished with an array instead of repeated code

2022-11-30 03:42 UTC, edwardhuahan commented on backend/src/main/java/com/speakfluid/backend/usecases/WozWozTranscriptAnalysisInteractor.java
> +                            for(Map.Entry<String, Double> entry : talkStepPair.entrySet()) {
Is it possible to implement this without adding another for loop? I'm aware that WozWozTranscriptAnalysisInteractor.java already contains multiple for loops

2022-12-01 01:22 UTC, Lemiex approved these changes
I know you encountered problems with this passing the maven tests for this PR; glad it worked out in the end! very thorough testing altho more detailed test names would be helpful. Overall wonderful job

2022-12-01 01:22 UTC, Lemiex commented on backend/src/main/java/com/speakfluid/backend/entities/ButtonStep.java
> +                this.scoreAccumulator += 2;
use ScoreStandards.mediumWeight or .low

2022-12-01 01:22 UTC, Lemiex commented on backend/src/main/java/com/speakfluid/backend/entities/ButtonStep.java
>                  this.scoreAccumulator += 2;
use ScoreStandards.mediumWeight or .low, no magic numbers

2022-12-01 01:22 UTC, Lemiex commented on backend/src/main/java/com/speakfluid/backend/entities/ButtonStep.java
>                  this.scoreAccumulator += 2;
Same for all of your other step entities^^

2022-12-01 01:22 UTC, Lemiex commented on backend/src/main/java/com/speakfluid/backend/entities/ConfidenceScoreCalculator.java
> +            return Math.round(confidenceScore * 100.0) / 100.0;
why are we dividing by 100 here? doesn't Math.round(confidenceScore * 100.0) give us the confidence score in percentage already or am i doing the math wrong

2022-12-01 01:22 UTC, Lemiex commented on backend/src/test/java/com/speakfluid/backend/entities/ButtonStepTests.java
> +    public void testButtonRunAnalysisDialogue2(){
it might be helpful to name these methods as what they are testing, like testButtonRunAnalysisHighScore

2022-12-01 01:22 UTC, Lemiex commented on backend/src/test/java/com/speakfluid/backend/entities/ConfidenceScoreOptimizerTests.java
> +        step3.put("Card", 20.0);
Nice! very thorough tests

2022-12-01 02:26 UTC, closed without merging